### ISSUE TITLE
"serv remove" error on ubuntu

### ISSUE THREAD

**Issue by maimon33** [nir0s/serv#4]
Can't remove dead service.

> ubuntu@vault-2:~$ sudo serv remove vault
> INFO - Removing upstart service vault...
> Traceback (most recent call last):
>   File "/usr/local/bin/serv", line 9, in <module>
>     load_entry_point('Serv==0.1.0', 'console_scripts', 'serv')()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in **call**
>     return self.main(_args, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, *_ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
>     return callback(_args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/serv/serv.py", line 388, in remove
>     Serv(init_system, verbose).remove(name)
>   File "/usr/local/lib/python2.7/dist-packages/serv/serv.py", line 175, in remove
>     init.stop()
>   File "/usr/local/lib/python2.7/dist-packages/serv/init/upstart.py", line 43, in stop
>     sh.stop(self.name)
>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1021, in __call__
>     return RunningCommand(cmd, call_args, stdin, stdout, stderr)
>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 486, in **init**
>     self.wait()
>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 500, in wait
>     self.handle_command_exit_code(exit_code)
>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 516, in handle_command_exit_code
>     raise exc(self.ran, self.process.stdout, self.process.stderr)
> sh.ErrorReturnCode_1: 

  RAN: '/sbin/stop vault'

  STDOUT:

  STDERR:
stop: Unknown instance:

**Comment by nir0s** [comment]
What does "dead" mean?

**Comment by nir0s** [comment]
#7 fixes this.
